version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.9.0
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      # - run:
      #     name: Unit tests
      #     command: npm run unit-tests
      # - run:
      #     name: Integration tests
      #     command: npm run integration-mock-run-ci

workflows:
  version: 2
  -deploy:
    jobs:
      - build
